"""empty message

Revision ID: f1f2d032bb4b
Revises: 
Create Date: 2024-10-30 19:41:51.386119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f2d032bb4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline',
    sa.Column('Airline_ID', sa.String(length=15), nullable=False),
    sa.Column('Airline_name', sa.String(length=100), nullable=False),
    sa.Column('Operating_Region', sa.String(length=50), nullable=False),
    sa.Column('Contact_Number', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('Airline_ID')
    )
    op.create_table('location',
    sa.Column('location_ID', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('location_ID')
    )
    op.create_table('airport',
    sa.Column('AP_CODE', sa.String(length=10), nullable=False),
    sa.Column('Airport_name', sa.String(length=100), nullable=False),
    sa.Column('location_ID', sa.Integer(), nullable=True),
    sa.Column('facilities', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['location_ID'], ['location.location_ID'], ),
    sa.PrimaryKeyConstraint('AP_CODE')
    )
    op.create_table('passenger',
    sa.Column('Passenger_ID', sa.Integer(), nullable=False),
    sa.Column('First_name', sa.String(length=20), nullable=False),
    sa.Column('Last_name', sa.String(length=20), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('Passport_number', sa.String(length=20), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=False),
    sa.Column('disabilities', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_ID', sa.Integer(), nullable=False),
    sa.Column('Contact_Number', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['location_ID'], ['location.location_ID'], ),
    sa.PrimaryKeyConstraint('Passenger_ID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('flight',
    sa.Column('Flight_ID', sa.Integer(), nullable=False),
    sa.Column('Flight_name', sa.String(length=20), nullable=False),
    sa.Column('Departure_Time', sa.DateTime(), nullable=False),
    sa.Column('Arrival_Time', sa.DateTime(), nullable=False),
    sa.Column('Year_of_Services', sa.Integer(), nullable=False),
    sa.Column('Airline_ID', sa.String(length=15), nullable=True),
    sa.Column('Origin_AP_CODE', sa.String(length=10), nullable=True),
    sa.Column('Destination_AP_CODE', sa.String(length=10), nullable=True),
    sa.Column('Flight_type', sa.String(length=20), nullable=False),
    sa.Column('Flight_Status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['Airline_ID'], ['airline.Airline_ID'], ),
    sa.ForeignKeyConstraint(['Destination_AP_CODE'], ['airport.AP_CODE'], ),
    sa.ForeignKeyConstraint(['Origin_AP_CODE'], ['airport.AP_CODE'], ),
    sa.PrimaryKeyConstraint('Flight_ID')
    )
    op.create_table('notification',
    sa.Column('Notification_ID', sa.Integer(), nullable=False),
    sa.Column('Passenger_ID', sa.Integer(), nullable=True),
    sa.Column('Message', sa.String(length=255), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Passenger_ID'], ['passenger.Passenger_ID'], ),
    sa.PrimaryKeyConstraint('Notification_ID')
    )
    op.create_table('services',
    sa.Column('Service_ID', sa.Integer(), nullable=False),
    sa.Column('Service_name', sa.String(length=100), nullable=False),
    sa.Column('Airport_ID', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['Airport_ID'], ['airport.AP_CODE'], ),
    sa.PrimaryKeyConstraint('Service_ID')
    )
    op.create_table('booking',
    sa.Column('Booking_ID', sa.Integer(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.Column('Payment_Status', sa.String(length=20), nullable=True),
    sa.Column('Boarding_time', sa.DateTime(), nullable=True),
    sa.Column('ChecK_in_time', sa.DateTime(), nullable=True),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Passenger_ID', sa.Integer(), nullable=True),
    sa.Column('Flight_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Flight_ID'], ['flight.Flight_ID'], ),
    sa.ForeignKeyConstraint(['Passenger_ID'], ['passenger.Passenger_ID'], ),
    sa.PrimaryKeyConstraint('Booking_ID')
    )
    op.create_table('flight__location',
    sa.Column('Flight_ID', sa.Integer(), nullable=False),
    sa.Column('location_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Flight_ID'], ['flight.Flight_ID'], ),
    sa.ForeignKeyConstraint(['location_ID'], ['location.location_ID'], ),
    sa.PrimaryKeyConstraint('Flight_ID', 'location_ID')
    )
    op.create_table('review',
    sa.Column('Review_ID', sa.Integer(), nullable=False),
    sa.Column('Flight_ID', sa.Integer(), nullable=True),
    sa.Column('Service_ID', sa.Integer(), nullable=True),
    sa.Column('Rating', sa.Integer(), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('Comment', sa.String(length=255), nullable=True),
    sa.Column('Passenger_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Flight_ID'], ['flight.Flight_ID'], ),
    sa.ForeignKeyConstraint(['Passenger_ID'], ['passenger.Passenger_ID'], ),
    sa.ForeignKeyConstraint(['Service_ID'], ['services.Service_ID'], ),
    sa.PrimaryKeyConstraint('Review_ID')
    )
    op.create_table('seat__matrix',
    sa.Column('Seat_ID', sa.Integer(), nullable=False),
    sa.Column('Flight_ID', sa.Integer(), nullable=True),
    sa.Column('Seat_Number', sa.String(length=5), nullable=False),
    sa.Column('Class', sa.String(length=20), nullable=True),
    sa.Column('Availability', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['Flight_ID'], ['flight.Flight_ID'], ),
    sa.PrimaryKeyConstraint('Seat_ID')
    )
    op.create_table('booking__services',
    sa.Column('Booking_ID', sa.Integer(), nullable=False),
    sa.Column('Service_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Booking_ID'], ['booking.Booking_ID'], ),
    sa.ForeignKeyConstraint(['Service_ID'], ['services.Service_ID'], ),
    sa.PrimaryKeyConstraint('Booking_ID', 'Service_ID')
    )
    op.create_table('cancellation',
    sa.Column('Cancellation_ID', sa.Integer(), nullable=False),
    sa.Column('Booking_ID', sa.Integer(), nullable=True),
    sa.Column('Request_time', sa.DateTime(), nullable=False),
    sa.Column('Issue_time', sa.DateTime(), nullable=False),
    sa.Column('Reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['Booking_ID'], ['booking.Booking_ID'], ),
    sa.PrimaryKeyConstraint('Cancellation_ID')
    )
    op.create_table('payment',
    sa.Column('Payment_ID', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Payment_Method', sa.String(length=20), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('Booking_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Booking_ID'], ['booking.Booking_ID'], ),
    sa.PrimaryKeyConstraint('Payment_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('cancellation')
    op.drop_table('booking__services')
    op.drop_table('seat__matrix')
    op.drop_table('review')
    op.drop_table('flight__location')
    op.drop_table('booking')
    op.drop_table('services')
    op.drop_table('notification')
    op.drop_table('flight')
    op.drop_table('passenger')
    op.drop_table('airport')
    op.drop_table('location')
    op.drop_table('airline')
    # ### end Alembic commands ###
