"""empty message

Revision ID: 315b4682052f
Revises: 
Create Date: 2024-11-22 04:02:56.334868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315b4682052f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
