"""empty message

Revision ID: 8de803c757c2
Revises: b392d5a6bc1e
Create Date: 2024-12-01 15:40:40.324611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de803c757c2'
down_revision = 'b392d5a6bc1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
