"""empty message

Revision ID: bbfa4a76fd5d
Revises: 8de803c757c2
Create Date: 2024-12-01 18:44:35.145883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbfa4a76fd5d'
down_revision = '8de803c757c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('Departure_Time',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('Arrival_Time',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('Arrival_Time',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('Departure_Time',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
