"""empty message

Revision ID: ebf3002d67ae
Revises: 315b4682052f
Create Date: 2024-11-25 11:13:11.306640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebf3002d67ae'
down_revision = '315b4682052f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('Boarding_time',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('Check_in_time',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)

    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.drop_index('Email')
        batch_op.drop_column('Email')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('Email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index('Email', ['Email'], unique=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('Check_in_time',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('Boarding_time',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
